// Code generated by protoc-gen-go. DO NOT EDIT.
// source: one.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	api "github.com/jgoodall/pb-test-two/v2/api"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test struct {
	A                    string          `protobuf:"bytes,1,opt,name=A,proto3" json:"A,omitempty"`
	B                    *api.TestOneTwo `protobuf:"bytes,2,opt,name=B,proto3" json:"B,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_322e57bd7c757107, []int{0}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *Test) GetB() *api.TestOneTwo {
	if m != nil {
		return m.B
	}
	return nil
}

func init() {
	proto.RegisterType((*Test)(nil), "one.api.Test")
}

func init() { proto.RegisterFile("one.proto", fileDescriptor_322e57bd7c757107) }

var fileDescriptor_322e57bd7c757107 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0xcf, 0x4b, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x31, 0x13, 0x0b, 0x32, 0xa5, 0x38, 0x4b, 0xca,
	0xf3, 0x21, 0x62, 0x4a, 0xe6, 0x5c, 0x2c, 0x21, 0xa9, 0xc5, 0x25, 0x42, 0x3c, 0x5c, 0x8c, 0x8e,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x8c, 0x8e, 0x42, 0x8a, 0x5c, 0x8c, 0x4e, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x20, 0xc5, 0x89, 0x05, 0x99, 0x7a, 0x20, 0x75, 0xfe,
	0x79, 0xa9, 0x21, 0xe5, 0xf9, 0x41, 0x8c, 0x4e, 0x4e, 0x1a, 0x51, 0x6a, 0xe9, 0x99, 0x25, 0x19,
	0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0x59, 0xe9, 0xf9, 0xf9, 0x29, 0x89, 0x39, 0x39, 0xfa,
	0x05, 0x49, 0xba, 0x25, 0xa9, 0xc5, 0x25, 0xba, 0xf9, 0x79, 0xa9, 0xfa, 0x65, 0x46, 0xfa, 0x89,
	0x05, 0x99, 0x49, 0x6c, 0x60, 0x9b, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x6f, 0x82,
	0xe2, 0x8a, 0x00, 0x00, 0x00,
}
